---
# tasks file for roles/restart_services

- name: Restart ElasticSearch services
  ansible.builtin.service:
    name: "elasticsearch"
    state: restarted
  when: inventory_hostname in groups['elastic_nodes']
  tags:
    - restart_elasticsearch

- name: Restart kibana services
  ansible.builtin.service:
    name: "kibana"
    state: restarted
  when: inventory_hostname in groups['kibana_nodes']
  tags:
    - restart_kibana

#- name: Stop Kibana services
#  ansible.builtin.service:
#    name: "kibana"
#    state: stopped
#  when: inventory_hostname in groups['kibana_nodes']
#
#- name: Start Kibana services
#  ansible.builtin.service:
#    name: "kibana"
#    state: started
#  when: inventory_hostname in groups['kibana_nodes']
