---
# tasks file for roles/cleanup

- name: "Remove locally fetched certificates"
  ansible.builtin.file:
    # path: "{{ tmp_dir }}/{{ cluster_name }}_certs.zip"
    #path: "/tmp/{{ cluster_name }}{{ item }}"
    path: "{{ tmp_dir }}"
    state: absent
  delegate_to: localhost
  with_items:
    - "{{ '_certs_pkcs12.zip' }}"
    - "{{ '_http_certificates.zip' }}"
    - "{{ '_fleet.zip' }}"
    - "{{ '_ca.pem' }}"
    - "{{ '_ca.p12' }} }}"
  tags:
    - create
    - install_es
    - debug

- name: "Remove remote certificates"
  ansible.builtin.file:
    path: "{{ es_cert_dir  }}"
    state: absent
  tags:
    - create
    - install_es
    - debug