---

- name: "Wait for SSH"
  ansible.builtin.wait_for_connection:
  tags:
    - create

- name: "Import elastic rpm key"
  ansible.builtin.rpm_key:
    state: 'present'
    key: 'https://artifacts.elastic.co/GPG-KEY-elasticsearch'
  tags:
    - create

- name: Print installer download locations
  ansible.builtin.debug:
    msg: "Downloading from: >{{ elastic_agent_installer_url }}< To: >{{ tmp_dir }}/elastic_agent-{{ es_version }}.rpm<"
  tags:
    - create

- name: "Check if file has already been downloaded"
  ansible.builtin.stat:
    path: "{{ tmp_dir }}/elastic_agent-{{ es_version }}.rpm"
  register: mb_file_exist
  tags:
    - create

- name: "Download installer"
  ansible.builtin.get_url:
    url: "{{ elastic_agent_installer_url }}"
    dest: "{{ tmp_dir }}/elastic_agent-{{ es_version }}.rpm"
    mode: '0440'
    validate_certs: false
  when: mb_file_exist.stat.exists == false
  tags:
    - create

- name: "Download sha512"
  ansible.builtin.get_url:
    url: "{{ elastic_agent_installer_sha_url }}"
    dest: "{{ tmp_dir }}/elastic_agent-{{ es_version }}.rpm.sha512"
    mode: '0440'
  tags:
    - create

- name: "Get sha256 sum of downloaded installer"
  ansible.builtin.stat:
    path: "{{ tmp_dir }}/elastic_agent-{{ es_version }}.rpm"
    checksum_algorithm: sha512
    get_checksum: true
  register: file_stat
  tags:
    - create

- name: "Register file hash"
  ansible.builtin.shell:
    cmd: "cat {{ tmp_dir }}/elastic_agent-{{ es_version }}.rpm.sha512 | awk '{print $1}'"
  register: file_hash
  tags:
    - create

- name: "Print hashes"
  ansible.builtin.debug:
    msg: "File Contents: >{{ file_hash.stdout }}< File Hash >{{ file_stat.stat.checksum }}<"
  tags:
    - create

- name: "Verify sha256sum of download before execution"
  ansible.builtin.fail:
    msg: "Failure, file is not correct."
  when: file_stat.stat.checksum != file_hash.stdout
  tags:
    - create

- name: "Install elastic agent"
  ansible.builtin.yum:
    name: "{{ tmp_dir }}/elastic_agent-{{ es_version }}.rpm"
    state: present
    disable_gpg_check: true
  tags:
    - create