---

- name: "Wait for SSH"
  ansible.builtin.wait_for_connection:
  tags:
    - create

#- name: "Create Fleet Policy"
#  ansible.builtin.uri:
#    url: "{{ kib_url }}/api/fleet/agent_policies?sys_monitoring=true"
#    method: POST
#    user: "{{ kib_user }}"
#    password: "HR+bYzX0delY6XmOwLM8"
#    validate_certs: false
#    # headers:
#    #   'kbn-xsrf': 'true'
#    #   'content-type': 'application/json'
#    body:
#      name: "{{ fleet_policy_name }}"
#      namespace: default
#      # monitoring_enabled: ["logs","metrics"]
#  tags:
#    - create
#    - fleet

#- name: "Create Fleet Policy"
#  ansible.builtin.shell:
#    cmd: "curl -k -u elastic:zkoFj1UKkfFd+wHA_jO7 --request POST --url {{ kib_url }}/api/fleet/agent_policies?sys_monitoring=true --header 'content-type: application/json' --header 'kbn-xsrf: true' --data '{\"name\":\"{{ fleet_policy_name }}\",\"namespace\":\"default\",\"monitoring_enabled\":[\"logs\",\"metrics\"]}'"
#  tags:
#    - create
#    - fleet
#    - fleet_policy

- name: "Deploy enroll-fleet-agent templates"
  ansible.builtin.template:
    src: "enroll-fleet-agent.sh.j2"
    dest: "{{ tmp_dir }}/enroll-fleet-agent.sh"
    mode: '0755'
  tags:
    - create
    - fleet

- name: "Execute fleet enroll script"
  ansible.builtin.shell:
    cmd: "{{ tmp_dir }}/enroll-fleet-agent.sh"
  tags:
    - create
    - fleet
