---


# curl -O -L http://artifacts.powellcompanies.com/elasticsearch//filebeat-8.10.2-x86_64.rpm
# curl -O -L http://artifacts.powellcompanies.com/elasticsearch/metricbeat-8.10.2-x86_64.rpm
# curl -O -L http://artifacts.powellcompanies.com/elasticsearch/auditbeat-8.10.2-x86_64.rpm
# curl -O -L http://artifacts.powellcompanies.com/elasticsearch/packetbeat-8.10.2-x86_64.rpm
# curl -O -L http://artifacts.powellcompanies.com/elasticsearch/elastic-agent-8.10.2-x86_64.rpm
# agent/password
- include: elastic_agent.yml
  # when: inventory_hostname in groups['fleet_nodes']
  tags: 
    - create

- name: "Create certs directory"
  ansible.builtin.file:
    path: "{{ es_cert_dir }}"
    state: directory
    owner: "root"
    group: "{{ svc_group }}"
    mode: "0770"
  tags:
    - create
    - install_kib
    - debug

- name: "Push new ES certs to nodes"
  ansible.builtin.copy:
    src: "{{ tmp_dir }}/{{ cluster_name }}{{ item }}"
    dest: "{{ es_cert_dir }}"
    owner: "root"
    group: "{{ svc_group }}}"
    mode: "0660"
  with_items:
    - "{{ '_certs_pkcs12.zip' }}"
    - "{{ '_http_certificates.zip' }}"
    - "{{ '_fleet.zip' }}"
    - "{{ '_ca.pem' }}"
    - "{{ '_ca.p12' }}"
  tags:
    - create
    - certs

# Include tasks in metricbeat.yml playbook
- include: metricbeat.yml
  tags: 
    - create
    - debug
    - install_beats
    - metricbeats

# - include: filebeat.yml
#   tags: 
#     - create
#     - debug
#     - install_beats
#     - filebeats

# - include: fleet.yml
#   when: inventory_hostname in groups['fleet_nodes']
#   tags: 
#     - create
#     - debug
#     - fleet

