---

- name: "Wait for SSH"
  ansible.builtin.wait_for_connection:

- name: "Import elastic rpm key"
  ansible.builtin.rpm_key:
    state: 'present'
    key: 'https://artifacts.elastic.co/GPG-KEY-elasticsearch'
  tags:
    - create

- name: Print installer download locations
  ansible.builtin.debug:
    msg: "Downloading from: >{{ metricbeat_installer_url }}< To: >{{ tmp_dir }}/metricbeat.rpm<"
  tags:
    - create

- name: "Check if file has already been downloaded"
  ansible.builtin.stat:
    path: "{{ tmp_dir }}/metricbeat.rpm"
  register: mb_file_exist
  tags:
    - create

- name: "Download installer"
  ansible.builtin.get_url:
    url: "{{ metricbeat_installer_url }}"
    dest: "{{ tmp_dir }}/metricbeat.rpm"
    mode: '0440'
    validate_certs: false
  when: mb_file_exist.stat.exists == False
  tags:
    - create

- name: "Download sha512"
  ansible.builtin.get_url:
    url: "{{ metricbeat_installer_sha_url }}"
    dest: "{{ tmp_dir }}/metricbeat.sha512"
    mode: '0440'
  tags:
    - create

- name: "Get sha256 sum of downloaded installer"
  ansible.builtin.stat:
    path: "{{ tmp_dir }}/metricbeat.rpm"
    checksum_algorithm: sha512
    get_checksum: true
  register: file_stat
  tags:
    - create

- name: "Register file hash"
  ansible.builtin.shell:
    cmd: "cat {{ tmp_dir }}/metricbeat.sha512 | awk '{print $1}'"
  register: file_hash
  tags:
    - create

- name: "Print hashes"
  ansible.builtin.debug:
    msg: "File Contents: >{{ file_hash.stdout }}< File Hash >{{ file_stat.stat.checksum }}<"
  tags:
    - create

- name: "Verify sha256sum of download before execution"
  ansible.builtin.fail:
    msg: "Failure, file is not correct."
  when: file_stat.stat.checksum != file_hash.stdout
  tags:
    - create

- name: "Install metricbeat"
  ansible.builtin.yum:
    name: "{{ tmp_dir }}/metricbeat.rpm"
    state: present
  tags:
    - create

- name: "Configure metricbeat"
  ansible.builtin.template:
    src: "metricbeat.yml.j2"
    dest: "/etc/metricbeat/metricbeat.yml"
    owner: root
    group: root
    mode: '0644'
  tags:
    - configure
    - create

- name: "Enable and start metricbeat service"
  ansible.builtin.service:
    name: metricbeat
    enabled: true
    state: started
  tags:
    - configure
    - create
