---
# tasks file for get_cluster_status

- name: "Have to get the password to do this which means we have to reset it..."
  import_tasks: ../reset_pw/tasks/main.yml
  tags: 
    - create
    - status

- name: Check cluster status
  ansible.builtin.uri:
    url: 'https://{{item}}:9200/_cluster/health?pretty=true'
    return_content: true
    url_username: 'elastic'
    url_password: '{{elasticpass.stdout}}'
    validate_certs: false
  register: response
  with_items:
    - "{{groups['cert_node']}}"
  tags: 
    - create
    - status

- name: Print cluster status
  ansible.builtin.debug:
    msg: "{{ response }}"
  tags: 
    - create
    - status

- name: Print elastic password
  ansible.builtin.debug:
    msg: "{{ elasticpass.stdout }}"
  tags: 
    - create
    - status

