---
# tasks file for get_cluster_status
- name: Check cluster status
  ansible.builtin.uri:
    url: 'https://{{item}}:9200/_cluster/health?pretty=true'
    return_content: true
    url_username: 'elastic'
    url_password: '{{elasticpass.stdout}}'
    validate_certs: false
  register: response
  with_items:
    - "{{groups['esmaster']}}"
  tags: 
    - create
    - install_es
    - status

- name: Print cluster status
  ansible.builtin.debug:
    msg: "{{ response }}"
  tags: 
    - create
    - install_es
    - status

- name: Print new elastic password
  ansible.builtin.debug:
    msg: "{{ elasticpass.stdout }}"
  tags: 
    - create
    - install_es
    - status