---
# tasks file for roles/create_cluster_token
- name: "Create kibana user and get password"
  ansible.builtin.shell:
    cmd: "/usr/share/elasticsearch/bin/elasticsearch-reset-password -u {{kib_user}} -ab | awk -F': ' '{print $2}'"
  register: kib_password
  when: inventory_hostname in groups['cert_node'] 
  tags:
    - create

- name: "Print kibana password"
  ansible.builtin.debug:
    msg: '{{kib_password.stdout}}'
  tags:
    - create

- name: "Export password"
  set_fact:
    kib_password: '{{kib_password}}'
  delegate_facts: true
  delegate_to: '{{item}}'
  with_items:
    - "{{groups['kibana_nodes']}}"
  tags:
    - create
 
- name: "Create admin users"
  ansible.builtin.uri:
    method: POST
    url: "https://{{ inventory_hostname }}:9200/_security/user/{{ item.username }}"
    user: "elastic"
    password: "4iZgeosmnMld+uL1focp"
    body: "{{ item | to_json }}"
    validate_certs: false
    body_format: json
  when: inventory_hostname in groups['cert_node']
  register: es_return
  loop:
    - { username: 'ppowell', password: '4iZgeosmnMld+uL1focp', roles: [ 'superuser' ], full_name: 'Patrick Powell', email: 'patrick.powell@elastic.co' }
  # delegate_to:
  #   localhost
  tags:
    - create
    - debug

- name: "Print es_return"
  ansible.builtin.debug:
    msg: '{{es_return}}'
  tags:
    - create
    - debug