---
# tasks file for roles/provision_vms
# Post VM deployment provisioning

- name: Wait for connection
  ansible.builtin.wait_for_connection:
  tags:
    - create
    - provision_vms

- name: Set hostnames
  ansible.builtin.hostname:
    name: '{{ inventory_hostname }}'
  tags:
    - create
    - provision_vms

- name: Print hostnames
  ansible.builtin.debug:
    msg: '{{ inventory_hostname }}'
  tags:
    - create
    - provision_vms

- name: Print IPs
  ansible.builtin.debug:
    msg: '{{ ansible_ssh_host | default(inventory_hostname) }}'
  tags:
    - create
    - provision_vms

- name: Install packages
  ansible.builtin.package:
    name: '{{item}}'
    state: 'present'
  loop:
    "{{packages}}"
  tags:
    - provision_vms
    - create

- name: Update
  ansible.builtin.package:
    name: '*'
    state: 'latest'
  tags:
    - create
    - provision_vms

- name: Disable SELinux
  ansible.posix.selinux:
    state: disabled
  register: se_changed
  tags:
    - create
    - provision_vms

- name: Print se_changed
  ansible.builtin.debug:
    msg: '{{ se_changed.reboot_required }}'
  tags: 
    - create

- name: check to see if we need a reboot
  command: needs-restarting -r
  register: needs_restart
  ignore_errors: true
  tags:
    - create

- name: display result
  debug:
    var: needs_restart.rc
  tags:
    - create

- name: Reboot Server if Necessary
  command: shutdown -r now "Ansible Updates Triggered"
  become: true
  async: 30
  poll: 0
  when: (needs_restart.rc == 1) or (se_changed.reboot_required)
  tags:
    - create

- name: Wait for connection
  ansible.builtin.wait_for_connection:
  tags:
    - create