---
# tasks file for roles/install_kibana

- name: "Import kibana rpm key"
  ansible.builtin.rpm_key:
    state: "present"
    key: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
  tags:
    - create
    - install_kib

- name: "Print installer download locations"
  ansible.builtin.debug:
    msg: "Downloading from: >{{ kib_installer_url }}< To: >{{ tmp_dir }}/kibana.rpm<"
  tags:
    - create

- name: "Check if file has already been downloaded"
  ansible.builtin.stat:
    path: "{{ tmp_dir }}/kibana.rpm"
  register: kib_file_exist
  tags:
    - create
    - install_kib

- name: "Download installer"
  ansible.builtin.get_url:
    url: "{{ kib_installer_url }}"
    dest: "{{ tmp_dir }}/kibana.rpm"
    mode: "0440"
    validate_certs: false
  when: kib_file_exist.stat.exists == false
  tags:
    - create
    - install_kib

- name: "Download sha512"
  ansible.builtin.get_url:
    url: "{{ kib_installer_sha_url }}"
    dest: "{{ tmp_dir }}/kibana.sha512"
    mode: "0440"
  tags:
    - create
    - install_kib

- name: "Get sha256 sum of downloaded installer"
  ansible.builtin.stat:
    path: "{{ tmp_dir }}/kibana.rpm"
    checksum_algorithm: "sha512"
    get_checksum: true
  register: file_stat
  tags:
    - create
    - install_kib

- name: "Register file hash"
  ansible.builtin.shell:
    cmd: "cat {{ tmp_dir }}/kibana.sha512 | awk '{print $1}'"
  register: file_hash
  tags:
    - create
    - install_kib

- name: "Print hashes"
  ansible.builtin.debug:
    msg: "File Contents: >{{ file_hash.stdout }}< File Hash >{{ file_stat.stat.checksum }}<"

- name: "Verify sha256sum of download before execution"
  ansible.builtin.fail:
    msg: "Failure, file is not correct."
  when: file_stat.stat.checksum != file_hash.stdout
  tags:
    - create
    - install_kib

- name: Disable IPV6
  ansible.posix.sysctl:
    name: '{{ item.setting }}'
    value: '{{ item.value }}'
    sysctl_set: true
  loop:
    - { setting: 'net.ipv6.conf.all.disable_ipv6', value: '1' }
    - { setting: 'net.ipv6.conf.default.disable_ipv6', value: '1' }
    - { setting: 'net.ipv6.conf.lo.disable_ipv6', value: '1' }
    - { setting: 'net.ipv6.conf.eth0.disable_ipv6', value: '1'}
  tags:
    - create
    - install_kib

- name: "Stop and disable firewalld"
  ansible.builtin.service:
    name: firewalld
    state: stopped
    enabled: false
  tags:
    - create
    - install_kib

- name: "Install kibana package"
  ansible.builtin.yum:
    name: '{{ tmp_dir }}/kibana.rpm'
    state: present
  register: install_out
  tags:
    - create
    - install_kib

- name: "Print installer output"
  ansible.builtin.debug:
    msg: "{{ install_out }}.split('\n') }}"
  tags:
    - create
    - install_kib
    - remove_kib

- name: "Deploy Kibana Configuration File"
  ansible.builtin.template:
    backup: true
    src: "kibana.yml.j2"
    dest: "/etc/kibana/kibana.yml"
    owner: "root"
    group: "kibana"
    mode: "0660"
  tags:
    - create
    - install_kib
    - deploy_template
    - debug

- name: "Create certs directory"
  ansible.builtin.file:
    path: "/etc/kibana/certs"
    state: directory
    owner: "root"
    group: "kibana"
    mode: "0770"
  tags:
    - create
    - install_kib
    - debug

- name: "Push certs to nodes"
  ansible.builtin.copy:
    src: "{{ tmp_dir }}{{ cluster_name }}_certs.zip"
    dest: "/etc/kibana/certs/{{ cluster_name }}_certs.zip"
    owner: "root"
    group: "kibana"
    mode: "0660"
  tags:
    - create
    - install_es
    - debug

- name: "Unzip cluster certificates file"
  ansible.builtin.unarchive:
    src: "/etc/kibana/certs/{{ cluster_name }}_certs.zip"
    dest: "/etc/kibana/certs/"
    remote_src: true
  tags:
    - create
    - install_es
    - debug

- name: "Generate key file"
  ansible.builtin.shell:
    cmd: "openssl pkcs12 -info -in /etc/kibana/certs/{{ ansible_nodename }}/{{ ansible_nodename }}.p12 >
      -passin pass:{{ TLS_Pass }} -nodes -nocerts -out /etc/kibana/certs/{{ ansible_nodename }}/{{ ansible_nodename }}.key"
    creates: "/etc/kibana/certs/{{ ansible_nodename }}/{{ ansible_nodename }}.key"
  tags:
    - create
    - install_kib
    - debug

- name: "Set permissions on key file"
  ansible.builtin.file:
    path: "/etc/kibana/certs/{{ ansible_nodename }}/{{ ansible_nodename }}.key"
    owner: "root"
    group: "kibana"
    mode: "0660"
  tags:
    - create
    - install_kib
    - debug

- name: "Generate .pem file"
  ansible.builtin.shell:
    cmd: "openssl pkcs12 -in /etc/kibana/certs/{{ ansible_nodename }}/{{ ansible_nodename }}.p12 -passin pass:{{ TLS_Pass }} >
      -out /etc/kibana/certs/{{ ansible_nodename }}/{{ ansible_nodename }}.pem -nodes -clcerts"
    creates: "/etc/kibana/certs/{{ ansible_nodename }}/{{ ansible_nodename }}.pem"
  tags:
    - create
    - install_kib
    - debug

- name: "Set permissions on .pem file"
  ansible.builtin.file:
    path: "/etc/kibana/certs/{{ ansible_nodename }}/{{ ansible_nodename }}.pem"
    owner: "root"
    group: "kibana"
    mode: "0660"
  tags:
    - create
    - install_kib
    - debug

- name: "Enable kibana"
  ansible.builtin.systemd:
    enabled: true
    name: "kibana.service"
  tags:
    - create
    - install_kib
    - debug

- name: "Start kibana"
  ansible.builtin.systemd:
    state: started
    name: "kibana.service"
  tags:
    - create
    - install_kib
    - debug

#- name: Print enrollment token
#  ansible.builtin.debug:
#    msg: "{{ elasticpass.stdout }}"
#  tags: 
#    - create
#    - install_kib