---
# tasks file for start_es

- name: "Start elasticsearch"
  ansible.builtin.systemd:
    state: restarted
    name: elasticsearch.service
  when: inventory_hostname in groups['data_nodes'] + groups['master_nodes'] + groups['ml_nodes']
  tags:
    - create