- name: Cleanup before we start
  hosts: esmaster
  gather_facts: false
  roles:
    - roles/cleanup

#- name: "Boot Template"
#  hosts: proxmox
#  gather_facts: false
#  roles:
#    - roles/boot_template
 
#- name: Update Template and shut back down
#  hosts: templates
#  become: yes
#  become_method: sudo
#  become_user: root
#  gather_facts: false
#  roles:
#    - roles/update_template

- name: Create a Proxmox VM's
  hosts: proxmox
  gather_facts: true
  roles:
    - roles/manage_vms
    
- name: Provision Proxmox VM's
  hosts: 
    - esnodes
    - esmaster
    - kibnodes
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: false
  roles:
    - roles/provision_vms

- name: Install Elasticsearch
  hosts: 
    - esnodes
    - esmaster
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: false
  roles:
    - roles/install_elastic

- name: Create Cluster Token
  hosts:
    - esmaster
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: false
  roles:
    - roles/manage_access

- name: Install Kibana
  hosts: 
    - kibnodes
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: true
  roles:
    - roles/install_kibana

- name: Cleanup when we're done
  hosts: esmaster
  gather_facts: false
  roles:
    - roles/cleanup

- name: Get Cluster Status
  hosts: 
    - esmaster
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: false
  roles:
    - roles/get_cluster_status