---

- name: Cleanup before we start
  hosts: certnode
  gather_facts: false
  roles:
    - roles/cleanup

- name: Create a Proxmox VM's
  hosts: proxmox
  gather_facts: true
  roles:
    - roles/manage_vms
    # tags:
    #   - create_vms
    
- name: Provision Proxmox VM's
  hosts: 
    - data_nodes
    - master_nodes
    - ml_nodes
    - kibana_nodes
    - fleet_nodes
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: false
  roles:
    - roles/provision_vms

- name: Install Elasticsearch
  hosts: 
    - seed_nodes
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: false
  roles:
    - roles/install_elastic

- name: Create and distribute Certificates to seed nodes
  hosts:
    - seed_nodes
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: false
  roles:
    - roles/manage_certs

- name: Start Elasticsearch Seed Nodes
  hosts: 
    - seed_nodes
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: false
  roles:
    - roles/start_elastic

# - name: Push Certificates
#   hosts: certnode
#   gather_facts: false
#   roles:
#     - roles/push_certs
 
- name: Create Cluster Token
  hosts:
    - master_nodes
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: false
  roles:
    - roles/manage_access

- name: Get Cluster Status
  hosts: 
    - master_nodes
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: false
  roles:
    - roles/get_cluster_status

- name: Install Kibana
  hosts: 
    - kibana_nodes
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: false
  roles:
    - roles/install_kibana

#- name: Cleanup when we're done
#  hosts: certnode
#  gather_facts: false
#  roles:
#    - roles/cleanup


