---


- name: Cleanup before we start
  hosts: cert_node
  gather_facts: false
  roles:
    - roles/cleanup

- name: Create a Proxmox VM's
  hosts: proxmox
  gather_facts: true
  roles:
    - roles/manage_vms
    
- name: Provision Proxmox VM's
  hosts: 
    - data_nodes
    - master_nodes
    - ml_nodes
    - kibana_nodes
    - fleet_nodes
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: false
  roles:
    - roles/provision_vms

- name: Install Elasticsearch
  hosts: 
    - seed_nodes
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: false
  roles:
    - roles/install_elastic

- name: Create and distribute Certificates to seed nodes
  hosts:
    - seed_nodes
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: false
  roles:
    - roles/manage_certs

- name: Start Elasticsearch Seed Nodes
  hosts: 
    - seed_nodes
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: false
  roles:
    - roles/start_stop_elastic

# - name: Push Certificates
#   hosts: cert_node
#   gather_facts: false
#   roles:
#     - roles/push_certs
 
- name: Get Cluster Status
  hosts: 
    - master_nodes
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: false
  roles:
    - roles/get_cluster_status

- name: Create Cluster Token
  hosts:
    - cert_node
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: false
  roles:
    - roles/manage_access

- name: Install Kibana
  hosts: 
    - kibana_nodes
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: false
  roles:
    - roles/install_kibana

- name: Install elastic_agent
  hosts: 
    - elastic_nodes
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: false
  roles:
    - roles/install_agents

- name: Cleanup when we're done
  hosts: cert_node
  gather_facts: false
  roles:
    - roles/cleanup


