---
# tasks file for reset_pw
- name: Get new password
  ansible.builtin.shell:
    cmd: "echo y | sudo /usr/share/elasticsearch/bin/elasticsearch-reset-password -u elastic 2>&1 | /usr/bin/grep 'New value' | /usr/bin/awk -F: '{print $2}' | /usr/bin/sed -e 's/^ //g'"
  register: elasticpass
  tags:
    - create
    - install_es
    - resetpw

- name: Export elastic password
  set_fact:
    elasticpass: '{{elasticpass}}'
  delegate_facts: true
  delegate_to: '{{item}}'
  with_items:
    - "{{groups['all']}}"
  tags:
    - create
    - resetpw

- name: Print new elastic password
  ansible.builtin.debug:
    msg: "{{ elasticpass.stdout }}"
  tags: 
    - create
    - resetpw